feat(eslint-ramda): add eslint configuration for Ramda
strvcom/code-quality-tools pull request #102
Opened 2020-05-03 15:58 UTC by developer239

Useful helpers for people who use Ramda in their projects. 🙂

2020-05-04 12:26 UTC, varholak-peter commented on packages/eslint-config-ramda/index.js
> +    'ramda/when-simplification': 'error'
```suggestion
    'ramda/when-simplification': 'error',
```

2020-05-05 19:06 UTC, developer239 commented on packages/eslint-config-ramda/index.js
> +    'ramda/when-simplification': 'error'
✅

2020-10-08 21:49 UTC, robertrossmann requested changes
Looks interesting, but after a brief glance through the plugin's docs it seems the rules are exclusively a code style or preference-based, therefore they should all be set to `warn` at most.

Also, please check compatibility with Node.js 12 and ESLint v7 and perhaps see if we can upgrade to their upcoming v3 or the plugin. 🙏 

Also, I will need you to take up the maintenance once this is merged. ❤️ Are you up for it?

2021-05-05 13:29 UTC, robertrossmann commented
Closing due to inactivity. Feel free to reopen if you ever find time to push this forward! 👍

2021-05-05 13:29 UTC, closed without merging